### PR TITLE
Update CMake to fit with new C files.

### PR DESCRIPTION
**Pull request by Swarthon**
I have tested it on Linux, but as I have not SFML installed on Windows, I have not done it there.

### CODE REVIEW

**Comment by HenryDane** [comment]
Thanks so much for the help!

**Comment by artillect** [comment]
@Swarthon How can I use this to compile the project? I'm new to this whole C development with libraries thing and have no clue where to start. (I'm on Linux BTW, with most recent CSFML, SFML, and GCC installed [as far as I can tell]).

**Comment by Swarthon** [comment]
First of all, you have to make sure you have cmake installed. Then,

1. Clone the repository.
2. Go into it with a command line.
3. Create a directory named `build` and go into there. This step is optional, some people like to compile in the source directory, but it doesn't keep it clean. 
4. Do `cmake ..` if you've done step 3, and `cmake .` elsewise.
5. Then `make`, and you got it.

**Comment by artillect** [comment]
I've been getting this error when building in codeblocks, and hoped cmake would solve it, unfortunately I still got it:

```
/usr/local/lib/libcsfml-window.so: undefined reference to `sf::String::operator std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >() const'
/usr/local/lib/libcsfml-audio.so: undefined reference to `sf::SoundStream::onLoop()'
/usr/local/lib/libcsfml-graphics.so: undefined reference to `sf::RenderWindow::setActive(bool)'
```

**Comment by HenryDane** [comment]
From what I have read, it seems entirely possible that for some reason the order in which the libraries are being included is incorrect. Could you post the command being used to build it? (I am not an SFML or CSFML expert.)

**Pull request merged**
